### ISSUE TITLE
`fetch` is deprecated, causing newer DBI drivers to not work with ETLUtils

### ISSUE THREAD

**Issue by mpancia** [jwijffels/ETLUtils#3]
The `fetch` function is deprecated as of 2015, per the [DBI documentation](http://www.inside-r.org/packages/cran/DBI/docs/dbFetch). This causes non-legacy-compatible DBI drivers to break, as they do not implement a `fetch` generic (e.g. the `bigrquery` DBI driver). 

The replacement is `dbFetch`, and likely could be swapped out in the `ETLUtils` code.

**Comment by jwijffels** [comment]
thanks for the notification and the fix!
