### ISSUE TITLE
 colClasses does not work

### ISSUE THREAD

**Issue by xiaoguozhi** [jwijffels/ETLUtils#8]
I find this parameter does not work . but i do not know why. I read the data from Oracle database by following.
my_dat <- read.odbc.ffdf(
query = "select * from testdata limit 10000",
odbcConnect.args = list(
dsn="smalltestsqlitedb", uid = "", pwd = "",
believeNRows = FALSE, rows_at_time = 1),
nrows = -1,
first.rows = 100, next.rows = 1000, VERBOSE = TRUE, colClasses=c(val1="factor"))
in Oracle, val1 is a character variable. However, it becomes double instead of factor. I want to know why this happen?

**Comment by jwijffels** [comment]
using colClasses does not make sense when getting data from a database as the data has already a strict structure. What you can do is the following

```
my_dat <- read.odbc.ffdf(
  query = "select * from testdata limit 10000",
  odbcConnect.args = list(dsn="smalltestsqlitedb", uid = "", pwd = "", believeNRows = FALSE, rows_at_time = 1), nrows = -1,
  first.rows = 100, next.rows = 1000, VERBOSE = TRUE, transFUN=function(x){
    x$val1 <- as.factor(x$val1)
    x
})
```
